name: Package Setup

on:
  push:
    branches: develop

permissions:
  contents: write

env:
  DOTNET_VERSION: '8.0.314' # The .NET SDK version to use
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # action runner's installed NuGet packages

jobs:

  build:

    name: build-windows
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      env:
        GH_TOKEN: ${{ github.token }}
      shell: pwsh
      run: |

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        cache: true
        cache-dependency-path: "./LotComWatcherSetup/packages.lock.json"

    - name: Install dependencies
      shell: pwsh
      run: dotnet restore
    
    - name: Install required workloads
      shell: pwsh
      run: |
        # install dotnet tools
        dotnet tool install --global wix
      
    - name: Build
      shell: pwsh
      run: |
        dotnet build
        # copy out build files
        New-Item -ItemType directory -Path "D:\a\Package" -ErrorAction SilentlyContinue
        cd D:\a\LotCom-watcher-setup\LotCom-watcher-setup\LotComWatcherSetup\bin\Debug\net472
        Copy-Item -Path "*" -Destination "D:\a\Package"

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_1 }}
      id: release-tag
      shell: pwsh
      run: |
        # get all tags sorted by version number
        $allTags = git tag --list | Sort-Object -Descending
        $latestTag = $allTags[0]
        $tag = $latestTag + 1
        
        # create github release and set default notes
        gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="$tag" --notes "Generated release"

        # set the output of this step to the VERSION_NUMBER environment var
        echo "RELEASE_TAG=$tag" >> $env:GITHUB_ENV
    
    - name: Upload Setup Package to release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_1 }}
      shell: pwsh
      run: |
        # use default tag for generated releases
        $tag = "$env:RELEASE_TAG"

        # upload the MSIX to the release
        Compress-Archive -Path "D:\a\Package" -DestinationPath "D:\a\Package\Setup.zip"
        gh release upload $tag "D:\a\Package\Setup.zip"